### ISSUE TITLE
Edit block on the survey builder is only available when logged in as admin

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#10]
Logged in as admin:

![image](https://user-images.githubusercontent.com/17750766/100737063-953b4800-33cb-11eb-9213-b99d128abead.png)

Logged in as s.rolph@wildsheffield.com (which has the survey builder role):
![image](https://user-images.githubusercontent.com/17750766/100737321-eba88680-33cb-11eb-8c6c-2cf1d29179d2.png)

**Comment by johnvanbreda** [comment]
Fixed - the Survey Admin role was missing the "Use contextual links" permission.
