### ISSUE TITLE
Attribute update failed: Not Found: .

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#11]
Not sure what caused this, I tried to remove an attribute

![image](https://user-images.githubusercontent.com/17750766/100738412-6de57a80-33cd-11eb-8658-f2b3de2d23d9.png)

**Comment by simonrolph** [comment]
Removing the attribute worked fine.

I wanted to give a different form label to a custom occurrence value 

![image](https://user-images.githubusercontent.com/17750766/100738625-c0269b80-33cd-11eb-86c9-9a654ff95fd8.png)

Where I wanted 'test' in the table header to change to 'Does more than 50% of the vegetation measure at least 50cm tall?'

If I press save I get 'The website encountered an unexpected error. Please try again later.'


I removed (through the remove block option) the occurrence value and pressed save which worked but the test heading was still in the table:
![image](https://user-images.githubusercontent.com/17750766/100738816-14318000-33ce-11eb-9e68-00181790753a.png)

reverted to defaults and I'm going to try again

**Comment by johnvanbreda** [comment]
I've just been through and setup a complete new test system (due to my laptop failing so I've setup an old one) and could not reproduce these problems. Let me know if still an issue - if so can you check the Drupal logs to see if there is anything there, and let me know what time?

**Comment by simonrolph** [comment]
Closed because irreproducible
