### ISSUE TITLE
Attribute update failed: Unauthorized: Attempt to PUT or DELETE record from another website.. 

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#12]
![image](https://user-images.githubusercontent.com/17750766/100740122-185e9d00-33d0-11eb-8a21-0a81b6fa841c.png)

This resulted when I tried to add this attribute:
![image](https://user-images.githubusercontent.com/17750766/100740214-3e843d00-33d0-11eb-9710-9216ca980ffe.png)

When I press save I get: `The website encountered an unexpected error. Please try again later.`

**Comment by johnvanbreda** [comment]
I couldn't reproduce this - masquerading as you. I've added this attribute to the "Does this work" form along with a grid so I can see it was OK. I applied a new version of the module this morning which fixed a few things though I don't think it related to this particular issue.

**Comment by simonrolph** [comment]
Closed because irreproducible
