### ISSUE TITLE
Explore page

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#17]
More of a 'would be good'.   Ability to add buffer i.e. 1km around point or grid ref in 'where' filter.

**Comment by johnvanbreda** [comment]
I've enabled this feature. It's newly developed so likely to change/improve in future. 
1. Go to the Filter Builder - Where popup.
2. Choose the "Points" tool on the map.
3. Enter a tolerance 
4. Click on the map.

**Comment by PeteTomlin** [comment]
Fantastic thanks
