### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#18]
Downloads for staff of sensitive records at full resolution not blurred. Blurring just for public and transfer to NBN etc.

**Comment by johnvanbreda** [comment]
We should probably actually switch to the newer, much faster Elasticsearch download tools. This is an hour or two's extra work.

**Comment by simonrolph** [comment]
John has updated the download page to use ElasticSearch and now downloads at original resolution.
