### ISSUE TITLE
Rename survey tabs

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#19]
Thinking about how user friendly current tabs are, they are somewhat similar so may need more distinction for non expert users. 

For example

Survey forms - surveys
Survey form templates - survey templates
add new survey form - template builder

**Comment by johnvanbreda** [comment]
@simonrolph are you happy to make these changes?

**Comment by simonrolph** [comment]
Yep 👍

**Comment by simonrolph** [comment]
Re organised
