### ISSUE TITLE
upload by csv not working

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#20]
Uploaded a csv of 78 dragonfly records but these have not appeared on the site. CSV upload didn't throw out any errors.

**Comment by johnvanbreda** [comment]
This may just be a case of the reporting system needing to catch up. We use one database for the raw data, then there is a background task that indexes everything into an Elasticsearch data store for reporting, this normally takes 20 minutes or so but can be a bit longer. I can see records such as this one have arrived OK: https://record.wildsheffield.com/details/record?occurrence_id=18362641

**Comment by PeteTomlin** [comment]
Ah, OK, thanks.  Old explore page saw them straight away so was able to check csv upload had worked.  Might be worth adding a bit of text to csv file upload page upon successful upload to say that records can take 20 minutes to appear.

**Comment by johnvanbreda** [comment]
This isn't just for CSV upload - any record addition will take a little while to appear on the Elasticsearch reporting pages. Should we add some text at the top of https://record.wildsheffield.com/explore/myrecords?
