### ISSUE TITLE
Indicia form control for delete record?

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#25]
At the moment we can't delete records from custom surveys?

**Comment by johnvanbreda** [comment]
Correct - it's not been implemented for the single record form, though I guess it should be at some point.

**Comment by johnvanbreda** [comment]
This is now done, but need to FTP up a new version of the layout builder module.

**Comment by johnvanbreda** [comment]
Code update now done so you should have delete buttons on the form.
