### ISSUE TITLE
Sites uploaded through warehouse appear under Simon's account under 'my sites' - is this a problem?

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#3]
What happens if I delete it from 'my sites'?

**Comment by simonrolph** [comment]
![image](https://user-images.githubusercontent.com/17750766/100101773-97952380-2e5a-11eb-8e85-76833378e2b0.png)

**Comment by johnvanbreda** [comment]
I've added a filter so only sites added through the My Sites interface will appear.

**Comment by simonrolph** [comment]
Great, thanks John
