### ISSUE TITLE
'Elasticsearch query failed' error on 'activities' and 'my records'

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#30]
Logged in as simon.rolph@wildsheffield.com, if I navigate to:
https://record.wildsheffield.com/activity/summary?group_id=1830&implicit=t

I get this error:
![image](https://user-images.githubusercontent.com/17750766/107354615-47774600-6ac6-11eb-890a-cdb02dbb9351.png)

Activity summary is meant to be visible to all.

This was raised by a user called Sandra, if I masquerade as her and go to 'my records' I get the same error:
![image](https://user-images.githubusercontent.com/17750766/107354848-945b1c80-6ac6-11eb-91fb-69d286194093.png)

As well as when going to the OAG activity summary (https://record.wildsheffield.com/activity/summary?group_id=1830&implicit=t).

If I go to https://record.wildsheffield.com/explore/myrecords-v1 the legacy page I can see that she has added records, but they were on the 1st and 2nd of feb so it can't be a caching issue because it wouldn't take that long. I've cleared the indicia cache anyway just to be sure but it made no difference.

**Comment by johnvanbreda** [comment]
I've fixed the permissions issues. 

Regarding Sandra's data not being on My Records, I think the primary issue here is that they were imported by Pete, so belong to his account. Even though the Recorder Name is provided as Sandra's, the system can't automatically assign records to her account as there will be problems with name duplication etc.

**Comment by simonrolph** [comment]
Thanks John, was aware that most of Sandra's records weren't submitted through her new account. We will at some point be looking to link previous anonymous records to user accounts which you said was possible but needs you to run a custom query.

What would the best way to do this? If I downloaded all our data and processed it in R to give you a spreadsheet with a column for record ID and a column for user ID would you be able to run the query from that?

**Comment by johnvanbreda** [comment]
@simonrolph yes, if you can do that it would be fairly easy for me.

**Comment by simonrolph** [comment]
Ok thanks I will close this issue and open another to send you a list of record and user IDs
