### ISSUE TITLE
Encourage more users to make accounts

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#31]
What would be the best way to include some text at the top of the casual record / list of records pages, which only shows if a user is not logged in, which reminds people to log in if they haven't logged in or create an account?

**Comment by johnvanbreda** [comment]
On the Edit tab, find the Form Structure. There is already a message displayed in the =About you= section which will only appear if logged out so this can be edited.

**Comment by simonrolph** [comment]
Updated text to both casual and list records pages to:

?You are currently not logged in. Did you know that you can create an Nature Counts account which allows you keep track and edit your records? <a href="/user/login">Log in</a> or <a href="/user/register">create an account</a>. <br>These records are being submitted to <a href="http://www.wildsheffield.com/" target="_top"><strong>Sheffield & Rotherham Wildlife Trust</strong></a>. Please make sure you read the <a href="/terms-conditions">Terms and conditions</a> before proceeding.?
