### ISSUE TITLE
Formatting of link in 'Activities' page

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#32]
The links all seem to be on one line of text so it can be quite hard to read. I couldn't find any options to fix this as drupal admin.

![image](https://user-images.githubusercontent.com/17750766/107391029-36dbc580-6af0-11eb-85ba-4828ef466e95.png)

**Comment by johnvanbreda** [comment]
This required a CSS change which I've done for you. In future if you want to understand the CSS structure of the theme so you can do this yourself let me know.

**Comment by simonrolph** [comment]
Great, the button layout looks much better!
