### ISSUE TITLE
Add to my activities star doesn't work

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#33]
Clicking the add to my activities star just takes you to your profile page and when you go back to Activities you haven't joined the activity.

Same as if you copy the URL https://record.wildsheffield.com/join/nature-detectives into the browser

I've set the activity to 'Anyone can join without needing approval'

**Comment by johnvanbreda** [comment]
Now fixed.

**Comment by simonrolph** [comment]
Hi @johnvanbreda 

It now successfully takes me to this page, for example:
![image](https://user-images.githubusercontent.com/17750766/108094764-132bf880-7077-11eb-9e08-d37bc1f14725.png)

but when I click Join I get this page:
![image](https://user-images.githubusercontent.com/17750766/108094853-26d75f00-7077-11eb-829e-d70f0c820718.png)
