### ISSUE TITLE
Ts&Cs page not working

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#35]
Ts & Cs page not working -  Also needs to be visible for public users who now have log in. 

https://record.wildsheffield.com/record/terms-conditions

**Comment by johnvanbreda** [comment]
Link should be https://record.wildsheffield.com/terms-and-conditions. Where did you get that link from @PeteTomlin?

**Comment by PeteTomlin** [comment]
I went through the link at the top of the list of records page.

**Comment by johnvanbreda** [comment]
There's a link in the footer, I can't see one at the top?

**Comment by PeteTomlin** [comment]
Its on the version for public that have not signed in.

**Comment by johnvanbreda** [comment]
Thanks @PeteTomlin - a missing / character. Now sorted.
