### ISSUE TITLE
How do you delete an old activity?  

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#39]

**Comment by johnvanbreda** [comment]
The best way to do this is to tick "Include date fields" on the Edit tab which means you can then set a start and end date on an activity. Then you can set an expiry date in the past. This way, the activity still exists, but cannot be found.

**Comment by PeteTomlin** [comment]
Thanks.  It was for a test activity I created.  That said I think I can edit it to be an actual activity from now.
