### ISSUE TITLE
Explore activity records doesn't seem to work for non-admin users

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#40]
Activity: Owlthorpe Fields Action Group

It's a closed group so I've made it so that members can explore records:
![image](https://user-images.githubusercontent.com/17750766/108843096-23d9f280-75d2-11eb-9c70-e2998bf9c2bb.png)

But masquerading as user OAGSFS and following the link to explore activity records ( https://record.wildsheffield.com/activity/explore?group_id=1830&implicit= ) gives the 'Elasticsearch query failed' dialogue box

Here's the log:
![image](https://user-images.githubusercontent.com/17750766/108843015-073dba80-75d2-11eb-958a-ba7ef6d9a6c0.png)

**Comment by johnvanbreda** [comment]
Permissions fixed - should be OK now.
