### ISSUE TITLE
What does records are private do?

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#41]
![image](https://user-images.githubusercontent.com/17750766/109475477-ab5db080-7a6d-11eb-94d9-5326a9f07ad7.png)

@johnvanbreda we're running a bioblitz, should we tick this box?

**Comment by johnvanbreda** [comment]
Normally the private records option is used for things like consultancy projects where the contract says records cannot be released to the public domain until the project is complete. For a BioBlitz you want to leave the records publically available surely? 

The Edit tab for the groups editing page will allow you to remove this option entirely if you don't think it's useful for the site.

**Comment by simonrolph** [comment]
Thanks John, useful to know 👍
