### ISSUE TITLE
What does the members search box on 'My Activities' do?

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#43]
![image](https://user-images.githubusercontent.com/17750766/110147466-9b2e3400-7dd3-11eb-9702-50fc8a5e6570.png)

I can't seem to make it do anything useful, just wondering what it does

Thanks

**Comment by johnvanbreda** [comment]
Good question - I think it's just a case of generic code auto-generating a filter box based on the system's knowledge of the report column output. As this column is a text column (not a simple number, as it contains text) it gives you a text filter option, but unless you understand the format of the links it's useless.
I'll remove it the next time the warehouse gets a full code update.
