### ISSUE TITLE
'My sites' page, what does location_type_ids

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#46]
![image](https://user-images.githubusercontent.com/17750766/111342579-8030af00-8672-11eb-9676-f370b7e84cdb.png)

What does 1371 refer to?

Do I need to change location_type_ids for different websites?

Thanks

**Comment by johnvanbreda** [comment]
It's a parameter to the report used to produce the list of sites. 1371 is a location type called "personal recording site" which is the location type ID we are using for user-created sites. There is no need to change it for the other website clones.
