### ISSUE TITLE
sample:licence_id do I need to change this if a nature counts site uses a different CC licence? 

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#47]
![image](https://user-images.githubusercontent.com/17750766/114163291-e9c67500-9921-11eb-9b8f-055ec6b7ede7.png)

**Comment by simonrolph** [comment]
@johnvanbreda ? thanks

**Comment by johnvanbreda** [comment]
Yes, that's setting the licence ID attached to all records input via this form. 

Here's the list of licences from the warehouse:
1	"Creative Commons Attribution"	"CC BY"
2	"Creative Commons Attribution-NonCommercial"	"CC BY-NC"
3	"Creative Commons "No Rights Reserved""	"CC0"
4	"Open Government licence (UK)"	"OGL"
5	"Creative Commons Attribution-ShareAlike"	"CC BY-SA"
6	"Creative Commons Attribution-NoDerivatives"	"CC BY-ND"
7	"Creative Commons Attribution-NonCommercial-ShareAlike "	"CC BY-NC-SA"
8	"Creative Commons Attribution-NonCommercial-NoDerivs"	"CC BY-NC-ND"
9	""All Rights Reserved""	"ARR"

We could potentially add others if necessary.

**Comment by simonrolph** [comment]
Thanks John, the other trusts have all gone for option 1 or 2 so no need to add any extras.
