### ISSUE TITLE
Configuring location autofill

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#48]
So in the SRWT site, searching for a nature reserve in the location box brings up nature reserves. How do I configure this for other Nature Counts sites? @johnvanbreda 

These are the options I can see: 
![image](https://user-images.githubusercontent.com/17750766/114697229-8e2b2b80-9d15-11eb-9e3d-f7b31c1cf0ac.png)

Thanks

**Comment by johnvanbreda** [comment]
At the moment, the report used is set to a custom one (projects/wildsheffield/my_sites_lookup). This hard codes the response to include the user's own sites, plus any sites of site type 14689 (SRWT site). Perhaps I should add the generic "Wildlife Trust Reserve" type that we setup to the report filter?

**Comment by simonrolph** [comment]
If you could add the Wildlife Trust Reserve type to that report filter that would be great. I don't have access to reports because reports are kept on the warehouse? (from what I can work on out on here: https://indicia-docs.readthedocs.io/en/latest/developing/reporting/index.html )

**Comment by simonrolph** [comment]
Hi @johnvanbreda I've got sites uploaded to some other Trust's sites so I can test this out when you get time to add the Wildlife Trust Reserve (ID: 17965) location type to the autofill report. Thanks

**Comment by johnvanbreda** [comment]
Now done.

**Comment by simonrolph** [comment]
Hi John doesn't seem to be working at the moment

For example
On this page https://record.nottinghamshirewildlife.org/record/casual-record
No sites are showing in the autocomplete but I have uploaded sites eg:
![image](https://user-images.githubusercontent.com/17750766/115427965-d5c02480-a1f9-11eb-9bd9-df35ce06a902.png)

Does it take time for the report to refresh? I've cleared the indicia cache 

Is it a permissions issue? the website IDs are: 

129
127
128
133
132

**Comment by johnvanbreda** [comment]
A mistake in my report logic - I'd allowed Wildlife Trust sites, but only when created by the user. Now fixed.

**Comment by simonrolph** [comment]
Great, thanks 🙂
