### ISSUE TITLE
Bots making accounts

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#5]
For example:
![image](https://user-images.githubusercontent.com/17750766/100115997-201bc000-2e6b-11eb-9af2-5b4d814abfc9.png)

tweak honeypot?

This useful page: https://indicia-docs.readthedocs.io/en/latest/administrating/drupal/preventing-spam.html

**Comment by simonrolph** [comment]
Honeypot wasn't enabled so I have enabled it now:

![image](https://user-images.githubusercontent.com/17750766/100116209-5d804d80-2e6b-11eb-9dcc-4ae374a88c98.png)

**Comment by johnvanbreda** [comment]
Honeypot won't be 100% effective, so if you need something more substantial Captcha/Recaptcha is a possibility, though it does impact on the accessibility of the sign up experience.

**Comment by simonrolph** [comment]
Starting with the less intrusive modules first and have installed the spambot module so I'll see how that goes.

**Comment by johnvanbreda** [comment]
Ok. What sort of rate of spam registration are you getting?

**Comment by simonrolph** [comment]
Before I enabled honeypot I was getting maybe 1-10 a week.

Since enabling honeypot last week I got one.

I've got it set up so I have to confirm any new accounts so there's no risk of them entering data into the forms.

**Comment by johnvanbreda** [comment]
I think no matter how stringent the anti-spam modules are, unless you confirm accounts manually one or two will always get through. In my experience bots won't actually post records as they don't know how to post a valid record, though you might get human spammers of course.

**Comment by simonrolph** [comment]
Added the math captcha but it doesn't seem to make much difference as I've gained 5 new bots today. Tried the google captcha but it produced an error (I think is the same error https://www.drupal.org/project/recaptcha/issues/3135854 ) and the solutions looked like too much work for the time being. To be revisited.

The robot wars continues...

**Comment by simonrolph** [comment]
Have successfully got the google captha to work, fix is here. https://www.drupal.org/project/recaptcha/issues/3135854 will see how this goes in terms of bot numbers

**Comment by johnvanbreda** [comment]
I've recently experienced an issue where Google Recaptcha v2 was being bypassed easily by spambots. If that happens, you can install recaptcha_v3 (a separate module) and it can be configured to use v2 as a fallback. So far this combination seems effective.

**Comment by simonrolph** [comment]
I set the v2 security preference to most secure and I haven't had any bots yet
![image](https://user-images.githubusercontent.com/17750766/115684685-7c6a0980-a34f-11eb-88ef-ff79ae2667f2.png)
