### ISSUE TITLE
File support for audio files for bats in Nature Counts

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#55]
Link to bat conservation trust form

https://www.brc.ac.uk/irecord/enter-bat-record?implicit=t&group_id=696

**Comment by johnvanbreda** [comment]
The form on iRecord has the following config for it's photos control:
```
@mediaTypes=["Image:Local","Audio:Local","Audio:SoundCloud"]
```

This can easily be copied over for standard Indicia forms. For the layout builder form type I would need to add an option to the code so you can access this setting in the configuration - about half an hour's work for me.

**Comment by simonrolph** [comment]
Added 
`@mediaTypes=["Image:Local","Audio:Local"]`
to casual record and list of record pages

**Comment by johnvanbreda** [comment]
@simonrolph if this comes up, another possibility is ZeroCrossing (*.zc) file format which is often used in bat detection.
