### ISSUE TITLE
You are not longer participating in {!}! template error

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#6]
Templating error on the message that appears when you leave an activity
![image](https://user-images.githubusercontent.com/17750766/100724536-e42cb180-33ba-11eb-8075-675bdcf2d862.png)

**Comment by simonrolph** [comment]
Probably because the activity is no longer visible?
![image](https://user-images.githubusercontent.com/17750766/100725086-7fbe2200-33bb-11eb-9f39-8c03223ac8b4.png)

**Comment by johnvanbreda** [comment]
I've fixed a typo in the message string's replacement token.
