### ISSUE TITLE
'ERROR: current transaction is aborted' on submitting records to custom survey form

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#61]
Problem submitting records to: https://record.wildsheffield.com/node/55

(This form works fine: https://record.wildsheffield.com/node/56 )

occurrence general - There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - SELECT "core_validation_rules" FROM surveys WHERE "id" = '642'
sample general - <strong>An error occurred</strong><br/>There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - INSERT INTO cache_occurrences_functional( id, sample_id, website_id, survey_id, input_form, location_id, location_name, public_geom, date_start, date_end, date_type, created_on, updated_on, verified_on, created_by_id, group_id, taxa_taxon_list_id, preferred_taxa_taxon_list_id, taxon_meaning_id, taxa_taxon_list_external_key, family_taxa_taxon_list_id, taxon_group_id, taxon_rank_sort_order, record_status, record_substatus, certainty, query, sensitive, release_status, marine_flag, freshwater_flag, terrestrial_flag, non_native_flag, data_cleaner_result, training, zero_abundance, licence_id, import_guid, confidential, external_key, taxon_path, blocked_sharing_tasks, parent_sample_id, verification_checks_enabled, media_count, identification_difficulty) SELECT distinct on (o.id) o.id, o.sample_id, o.website_id, s.survey_id, COALESCE(sp.input_form, s.input_form), s.location_id, case when o.confidential=true or o.sensitivity_precision is not null or s.privacy_precision is not null then null else coalesce(l.name, s.location_name, lp.name, sp.location_name) end, reduce_precision(coalesce(s.geom, l.centroid_geom), o.confidential, greatest(o.sensitivity_precision, s.privacy_precision)) as public_geom, s.date_start, s.date_end, s.date_type, o.created_on, o.updated_on, o.verified_on, o.created_by_id, s.group_id, o.taxa_taxon_list_id, cttl.preferred_taxa_taxon_list_id, cttl.taxon_meaning_id, cttl.external_key, cttl.family_taxa_taxon_list_id, cttl.taxon_group_id, cttl.taxon_rank_sort_order, o.record_status, o.record_substatus, case when certainty.sort_order is null then null when certainty.sort_order <100 then 'C' when certainty.sort_order <200 then 'L' else 'U' end, null, o.sensitivity_precision is not null, o.release_status, cttl.marine_flag, cttl.freshwater_flag, cttl.terrestrial_flag, cttl.non_native_flag, null, o.training, o.zero_abundance, s.licence_id, o.import_guid, o.confidential, o.external_key, ctp.path, CASE WHEN u.allow_share_for_reporting AND u.allow_share_for_peer_review AND u.allow_share_for_verification AND u.allow_share_for_data_flow AND u.allow_share_for_moderation AND u.allow_share_for_editing THEN null ELSE ARRAY_REMOVE(ARRAY[ CASE WHEN u.allow_share_for_reporting=false THEN 'R' ELSE NULL END, CASE WHEN u.allow_share_for_peer_review=false THEN 'P' ELSE NULL END, CASE WHEN u.allow_share_for_verification=false THEN 'V' ELSE NULL END, CASE WHEN u.allow_share_for_data_flow=false THEN 'D' ELSE NULL END, CASE WHEN u.allow_share_for_moderation=false THEN 'M' ELSE NULL END, CASE WHEN u.allow_share_for_editing=false THEN 'E' ELSE NULL END ], NULL) END, s.parent_id, w.verification_checks_enabled, (SELECT COUNT(om.*) FROM occurrence_media om WHERE om.occurrence_id=o.id AND om.deleted=false), (SELECT cts.identification_difficulty FROM cache_taxon_searchterms cts where cts.taxa_taxon_list_id=o.taxa_taxon_list_id AND cts.simplified=false) FROM occurrences o LEFT JOIN cache_occurrences_functional co on co.id=o.id JOIN websites w ON w.id=o.website_id AND w.deleted=false JOIN samples s ON s.id=o.sample_id AND s.deleted=false LEFT JOIN samples sp ON sp.id=s.parent_id AND sp.deleted=false LEFT JOIN locations l ON l.id=s.location_id AND l.deleted=false LEFT JOIN locations lp ON lp.id=sp.location_id AND lp.deleted=false JOIN users u ON u.id=o.created_by_id AND u.deleted=false JOIN cache_taxa_taxon_lists cttl ON cttl.id=o.taxa_taxon_list_id LEFT JOIN cache_taxon_paths ctp ON ctp.external_key=cttl.external_key AND ctp.taxon_list_id=15 LEFT JOIN (occurrence_attribute_values oav JOIN termlists_terms certainty ON certainty.id=oav.int_value JOIN occurrence_attributes oa ON oa.id=oav.occurrence_attribute_id and oa.deleted='f' and oa.system_function='certainty' ) ON oav.occurrence_id=o.id AND oav.deleted='f' WHERE o.deleted=false AND co.id IS NULL and o.id in (20426909)

Cleared the indicia cache then got:

occurrence general - There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - SELECT "core_validation_rules" FROM surveys WHERE "id" = '642'
sample general - <strong>An error occurred</strong><br/>There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - INSERT INTO cache_samples_functional( id, website_id, survey_id, input_form, location_id, location_name, public_geom, date_start, date_end, date_type, created_on, updated_on, verified_on, created_by_id, group_id, record_status, training, query, parent_sample_id, media_count) SELECT distinct on (s.id) s.id, su.website_id, s.survey_id, COALESCE(sp.input_form, s.input_form), s.location_id, CASE WHEN s.privacy_precision IS NOT NULL THEN NULL ELSE COALESCE(l.name, s.location_name, lp.name, sp.location_name) END, reduce_precision(coalesce(s.geom, l.centroid_geom), false, s.privacy_precision), s.date_start, s.date_end, s.date_type, s.created_on, s.updated_on, s.verified_on, s.created_by_id, s.group_id, s.record_status, s.training, case when sc1.id is null then null when sc2.id is null and s.updated_on<=sc1.created_on then 'Q' else 'A' end, s.parent_id, (SELECT COUNT(sm.*) FROM sample_media sm WHERE sm.sample_id=s.id AND sm.deleted=false) FROM samples s LEFT JOIN cache_samples_functional cs on cs.id=s.id LEFT JOIN samples sp ON sp.id=s.parent_id AND sp.deleted=false LEFT JOIN locations l ON l.id=s.location_id AND l.deleted=false LEFT JOIN locations lp ON lp.id=sp.location_id AND lp.deleted=false JOIN surveys su on su.id=s.survey_id and su.deleted=false LEFT JOIN sample_comments sc1 ON sc1.sample_id=s.id AND sc1.deleted=false AND sc1.query=true AND (s.verified_on IS NULL OR sc1.created_on>s.verified_on) LEFT JOIN sample_comments sc2 ON sc2.sample_id=s.id AND sc2.deleted=false AND sc2.query=false AND (s.verified_on IS NULL OR sc2.created_on>s.verified_on) AND sc2.id>sc1.id WHERE s.deleted=false AND cs.id IS NULL and s.id in (14409185)

**Comment by simonrolph** [comment]
Now I get:

sample general - <strong>An error occurred</strong><br/>There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - SELECT table_schema || '.' || table_name FROM information_schema.tables WHERE table_schema NOT IN ('pg_catalog', 'information_schema')

**Comment by johnvanbreda** [comment]
Should be sorted. It was a missing bit of code in the new layout builder which works out which attributes to use for detecting zero abundance - the unchecked booleans were triggering it treating each row as an absence record. It then posted without an ID causing an error.

**Comment by simonrolph** [comment]
Great, thanks @johnvanbreda 👍
