### ISSUE TITLE
Species lists reversed

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#62]
Species list as input: 
![image](https://user-images.githubusercontent.com/17750766/119326785-2fdd5b00-bc7a-11eb-837b-cbbbdb5f11f9.png)

Species list on survey form:
![image](https://user-images.githubusercontent.com/17750766/119326926-57342800-bc7a-11eb-99bd-62accba1be03.png)

This is important for creating Nature Counts versions of paper forms

**Comment by simonrolph** [comment]
But then when you go back to the species list input page its in a different order, but the survey form order persists 
![image](https://user-images.githubusercontent.com/17750766/119329215-e5a9a900-bc7c-11eb-9cce-4077623a3e6d.png)

**Comment by johnvanbreda** [comment]
Both issues now fixed - the code which loaded the list did not specify a sort in the query.
