### ISSUE TITLE
Activity summary -  sensitive records making the map unreadable

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#63]
![image](https://user-images.githubusercontent.com/17750766/120624102-404ebc00-c458-11eb-9343-52045b65fab6.png)

**Comment by johnvanbreda** [comment]
This should be significantly improved if we update the iform module as I worked on this for iRecord recently.

**Comment by johnvanbreda** [comment]
See what you think now @simonrolph?

**Comment by simonrolph** [comment]
Looks great thanks!

Is it possible to do something on the explore records pages as we can have a similar issue:
![image](https://user-images.githubusercontent.com/17750766/126150127-550b7770-14fb-4b1c-9173-54968ef7218e.png)

**Comment by johnvanbreda** [comment]
Done. I changed the config on this page to match iRecord as follows -
Under the User Interface, Form Structure configuration on the Edit tab, find the following:
```
@layerConfig=<!--{
  "recordsMap": {
    "title": "All records in current filter (grid map)",
    "source": "recordsGridSquares",
    "enabled": true,
    "type":"circle",
    "style": {
      "color": "#3333FF",
      "weight": 2,
      "fillOpacity": "metric",
      "size": "autoGridSquareSize"
    }
  },
  .....
```

I changed the weight setting to 1 (the line weight) and removed the fillOpactiy: metric setting. This allows a slightly more intelligent custom algorithm for setting square weight to be applied.
