### ISSUE TITLE
Trending species goes off the page

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#64]
![image](https://user-images.githubusercontent.com/17750766/120624295-79872c00-c458-11eb-845d-a3843b77bcf2.png)

**Comment by simonrolph** [comment]
eg https://record.wildsheffield.com/activity/summary?group_id=1830&implicit=

![image](https://user-images.githubusercontent.com/17750766/120624404-93287380-c458-11eb-8332-c3b0ea26ef92.png)

**Comment by johnvanbreda** [comment]
CSS change needed. I can also use a new cardGallery control for the photos on this tab.

**Comment by johnvanbreda** [comment]
Will be fixed by #75.

**Comment by johnvanbreda** [comment]
Now done. I'm pleased to say the photos look better too.
