### ISSUE TITLE
Drupal core update

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#74]

**Comment by johnvanbreda** [comment]
Is it OK to apply this at any time, assuming the site will be offline for 20 minutes or so @simonrolph ?

**Comment by johnvanbreda** [comment]
Also note the need to upgrade iform, may as well do at same time (#75)

**Comment by simonrolph** [comment]
Yes that's fine.

**Comment by johnvanbreda** [comment]
Done
