### ISSUE TITLE
Forms build with the survey builder are listed in the explore filters as Node #

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#81]
Example:

![image](https://user-images.githubusercontent.com/17750766/122589334-097fc500-d058-11eb-8304-97c7a6de4e5c.png)

Should have the name of the form

**Comment by johnvanbreda** [comment]
@simonrolph this is generated by the node's URL alias, since the node's title isn't stored anywhere in the Indicia database. To edit this, you can use the Edit tab's URL Alias setting for each survey form.
Once that is done let me know as I think I will need to update existing data to get rid of the node ... entries.

**Comment by simonrolph** [comment]
I've done it, they all have the url alias of /survey-forms/name-of-survey-form

Had to log in as admin to do it when ideally you'd be able to do it from 'survey admin' role.

I've added https://www.drupal.org/project/url_alias_permissions and added the appropriate permission
So it looks like this:
![image](https://user-images.githubusercontent.com/17750766/126323040-61b9fbf8-73b7-4fa8-8a29-884bb3d6f96c.png)

Although might be a suitable update to the survey builder to add the url alias based on the survey name on creation?

**Comment by johnvanbreda** [comment]
Rather than re-invent wheels, see https://www.drupal.org/project/pathauto.

I've sorted node/55's data. There are also samples linked to node/56 which I think is the Woodland monitoring invasives form, but node/56 doesn't seem to exist any more. Has it been deleted?

**Comment by simonrolph** [comment]
Thanks, will set up path auto for survey forms

Sorry yes the node 56 was an old form, I have gone into the warehouse and deleted the samples from it. And I have deleted the survey dataset too.

Survey form shows up nicely in the explore page filters.
