### ISSUE TITLE
non SRWT Attributes 

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#85]
I don't recognise these attributes in the survey builder, just wondering where they came from

![image](https://user-images.githubusercontent.com/17750766/125775443-32a50338-e2a2-4f04-95b4-ed61f0d9d925.png)

**Comment by johnvanbreda** [comment]
They are from the British Dragonfly Society's recording form - standard codes for Adults, Copulating pairs, Ovipositing, Larve, Exuviae, Emerging etc.
