### ISSUE TITLE
Partner Nature Counts sites broken after update

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#87]
I think the update is due to client helpers update.

Errors on indicia pages:
![image](https://user-images.githubusercontent.com/17750766/125954998-e8c4c004-b7b1-473b-a831-e24a20fa95ac.png)

The 404 is for https://record.mwt.im/modules/iform/media/js/fancybox/source/jquery.fancybox.pack.js?v=8.9.6

I ran update.php for the nottinghamshire site and now get these errors:
![image](https://user-images.githubusercontent.com/17750766/125955283-f2361e00-552c-4a31-bfa8-d5a97b728841.png)

I've put all sites into maintenance mode.

Any ideas what's happened here @johnvanbreda any site config changes? I was hoping the multisite would mean updates wouldn't be too much hassle but was probably wrong...

**Comment by simonrolph** [comment]
And this is what the site looks like: 
![image](https://user-images.githubusercontent.com/17750766/125956360-8dfcbd1d-7a18-493d-80e4-04c3e31b3925.png)

**Comment by johnvanbreda** [comment]
Try clearing the Drupal cache. There were some fairly significant updates in Indicia's JavaScript libraries not so long ago due to Drupal 9 compatiblity, so you are probably getting the old version running against the newer PHP code.

**Comment by simonrolph** [comment]
Thanks, that fixes the first error - I guess in a similar way to running update.php does but it's still showing this error about tabs:
![image](https://user-images.githubusercontent.com/17750766/125961877-68832713-f8a7-436c-b702-a17071b99f37.png)

If I email you a password for the manx site could you have a look? obviously include it in the allocated dev time

**Comment by johnvanbreda** [comment]
The newer version of iform now requires the jQuery UI and jQuery UI Tabs modules. Both are available on the Extend tab but need to be turned on manually, followed by yet another clear of the Drupal caches. That seems to have done the trick.

**Comment by johnvanbreda** [comment]
P.S. this was an unusually large Indicia module upgrade due to Drupal 9 support so hopefully this type of problem won't normally happen.

**Comment by simonrolph** [comment]
🥳 thanks John! I've fixed the other sites
